openapi: 3.0.1
info:
  title: getNames
  description: API Definition of getNames
  version: 1.0.0
servers:
- url: http://localhost:8290/getnames
paths:
  /:
    get:
      responses:
        default:
          description: Default response
